# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         TomTom-WEBFLEET-Connect
version:      2.11
version_from: lib/TomTom/WEBFLEET/Connect.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    Text::ParseWords:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
